server:
  port: 8003
spring:
  application:
    name: service-ws
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.58.223:3306/aqjianzhi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  redis:
    host: 39.105.58.223
    port: 6379
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

