server:
  port: 8002
spring:
  application:
    name: service-user
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/chat?serverTimezone=GMT%2B8
    username: root
    password: hahaha
  redis:
    host: 39.105.58.223
    port: 6379
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 39.105.58.223:8848


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/jz/aqjianzhi/task_service/mapper/xml/*.xml
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.jz.aqjianzhi.task_service.entity

